---
- name: "ovirt_exporter | Deploy ovirt_exporter options configuration"
  ansible.builtin.template:
    src: "ovirt_exporter.options.j2"
    dest: "/etc/conf.d/ovirt_exporter"
    owner: "root"
    group: "root"
    mode: "0644"
  when:
    - "hostvars[inventory_hostname]['ovirt_exporter'] is defined"
    - "hostvars[inventory_hostname]['ovirt_exporter'] != ''"
    - "hostvars[inventory_hostname]['ovirt_exporter'] |
       community.general.json_query(vars['ovirt_exporter_install_package'])
       is defined"
    - "hostvars[inventory_hostname]['ovirt_exporter'] |
       community.general.json_query(vars['ovirt_exporter_install_package'])
       == 'true'"
  vars:
    ovirt_exporter_install_package: "[] |
      map(&install_package || 'false', @) | [0]"
  notify:
    - "Restart ovirt_exporter"
- name: "ovirt_exporter | Deploy ovirt_exporter service configuration"
  ansible.builtin.template:
    src: "ovirt_exporter.service.j2"
    dest: "{{ '/etc/systemd/system/' +
      hostvars[inventory_hostname]['ovirt_exporter_service'] + '.service' }}"
    owner: "root"
    group: "root"
    mode: "0644"
  when:
    - "hostvars[inventory_hostname]['ovirt_exporter'] is defined"
    - "hostvars[inventory_hostname]['ovirt_exporter'] != ''"
    - "hostvars[inventory_hostname]['ovirt_exporter'] |
       community.general.json_query(vars['ovirt_exporter_install_package'])
       is defined"
    - "hostvars[inventory_hostname]['ovirt_exporter'] |
       community.general.json_query(vars['ovirt_exporter_install_package'])
       == 'false'"
  vars:
    ovirt_exporter_install_package: "[] |
      map(&install_package || 'false', @) | [0]"
  notify:
    - "Daemon reload"
    - "Restart ovirt_exporter"
- name: "ovirt_exporter | Enable ovirt_exporter"
  ansible.builtin.systemd:
    name: "{{ hostvars[inventory_hostname]['ovirt_exporter_service'] }}"
    enabled: "yes"
  when:
    - "hostvars[inventory_hostname]['ovirt_exporter'] is defined"
    - "hostvars[inventory_hostname]['ovirt_exporter'] != ''"
    - "hostvars[inventory_hostname]['ovirt_exporter'] |
       community.general.json_query(vars['ovirt_exporter_enable']) is
       defined"
    - "hostvars[inventory_hostname]['ovirt_exporter'] |
       community.general.json_query(vars['ovirt_exporter_enable']) == 'true'"
  vars:
    ovirt_exporter_enable: "[] | map(&enable || 'false', @) | [0]"
