---
- name: "ovirt_exporter | Install the required packages in Redhat
    derivatives"
  ansible.builtin.dnf:
    name: "{{ ovirt_exporter_pacakges_variant }}"
    state: "{{ vars['ovirt_exporter_package_state'] | default(omit) }}"
    update_cache: "yes"
  when:
    - "hostvars[inventory_hostname]['ansible_os_family'] == 'RedHat'"
- name: "ovirt_exporter | Install the required packages in Debian
    derivatives"
  ansible.builtin.apt:
    name: "{{ ovirt_exporter_pacakges_variant }}"
    state: "{{ vars['ovirt_exporter_package_state'] | default(omit) }}"
    update_cache: "yes"
  when:
    - "hostvars[inventory_hostname]['ansible_os_family'] == 'Debian'"
- name: "ovirt_exporter | Install the required packages in ArchLinux
    derivatives"
  community.general.pacman:
    name: "{{ ovirt_exporter_pacakges_variant }}"
    state: "{{ vars['ovirt_exporter_package_state'] | default(omit) }}"
    update_cache: "yes"
  when:
    - "hostvars[inventory_hostname]['ansible_os_family'] == 'Archlinux'"
